package com.github.tvbox.osc.util

/**
 * Material Symbols 图标工具类
 *
 * 使用方法：
 * 1. 在布局中使用 TextView 并应用样式：style="@style/Widget.App.MaterialSymbols"
 * 2. 设置文本为对应的图标代码：android:text="@string/ms_home"
 *
 * 或者在代码中：
 * textView.text = MaterialSymbols.HOME
 */
object MaterialSymbols {
    // 导航图标
    const val HOME = "\uE88A"
    const val SEARCH = "\uE8B6"
    const val SETTINGS = "\uE8B8"
    const val PERSON = "\uE7FD"
    const val FAVORITE = "\uE87D"
    const val HISTORY = "\uE889"
    const val EXPLORE = "\uE87A"
    const val DASHBOARD = "\uE871"
    const val ACCOUNT_CIRCLE = "\uF20B"
    const val ACCOUNT_BOX = "\uE851"
    const val GROUPS = "\uF233"
    const val CATEGORY = "\uE574"

    // 媒体控制图标
    const val PLAY_ARROW = "\uE037"
    const val PAUSE = "\uE034"
    const val STOP = "\uE047"
    const val SKIP_NEXT = "\uE044"
    const val SKIP_PREVIOUS = "\uE045"
    const val FAST_FORWARD = "\uE01F"
    const val FAST_REWIND = "\uE020"
    const val VOLUME_UP = "\uE050"
    const val VOLUME_DOWN = "\uE04D"
    const val VOLUME_OFF = "\uE04F"
    const val CLOSED_CAPTION = "\uE01C"
    const val REPEAT = "\uE040"
    const val REPEAT_ONE = "\uE041"
    const val SHUFFLE = "\uE043"
    const val PLAYLIST = "\uE5C3"
    const val QUEUE_MUSIC = "\uE03D"
    const val MUSIC_NOTE = "\uE405"
    const val VIDEO_LIBRARY = "\uE04A"
    const val MOVIE = "\uE02C"
    const val SLOW_MOTION_VIDEO = "\uE068"
    const val SPEED = "\uE9E4"

    // 操作图标
    const val ADD = "\uE145"
    const val REMOVE = "\uE15B"
    const val DELETE = "\uE872"
    const val EDIT = "\uE3C9"
    const val SHARE = "\uE80D"
    const val DOWNLOAD = "\uE2C0"
    const val UPLOAD = "\uE2C6"
    const val REFRESH = "\uE5D5"
    const val CLOSE = "\uE5CD"
    const val CHECK = "\uE876"
    const val INFO = "\uE88E"
    const val WARNING = "\uE002"
    const val ERROR = "\uE000"
    const val SAVE = "\uE161"
    const val SAVE_AS = "\uE161"
    const val SAVE_ALT = "\uE171"
    const val PRINT = "\uE8AD"
    const val SEND = "\uE163"
    const val REPLY = "\uE15E"
    const val REPLY_ALL = "\uE15F"
    const val FORWARD = "\uE154"
    const val ATTACH_FILE = "\uE226"
    const val ATTACH_EMAIL = "\uEA5E"
    const val CONTENT_COPY = "\uE14D"
    const val CONTENT_CUT = "\uE14E"
    const val CONTENT_PASTE = "\uE14F"

    // 界面元素图标
    const val MENU = "\uE5D2"
    const val MORE_VERT = "\uE5D4"
    const val MORE_HORIZ = "\uE5D3"
    const val ARROW_BACK = "\uE5C4"
    const val ARROW_FORWARD = "\uE5C8"
    const val ARROW_UP = "\uE5C7"
    const val ARROW_DOWN = "\uE5C5"
    const val EXPAND_LESS = "\uE5CE"
    const val EXPAND_MORE = "\uE5CF"
    const val FILTER_LIST = "\uE152"
    const val SORT = "\uE164"
    const val APPS = "\uE5C3"
    const val GRID_VIEW = "\uE9B0"
    const val LIST = "\uE896"
    const val VIEW_LIST = "\uE8EF"
    const val VIEW_MODULE = "\uE8F0"
    const val VIEW_QUILT = "\uE8F1"
    const val VIEW_STREAM = "\uE8F2"
    const val VIEW_DAY = "\uE8ED"
    const val VIEW_WEEK = "\uE8F3"
    const val VIEW_AGENDA = "\uE8E9"
    const val VIEW_ARRAY = "\uE8EA"
    const val VIEW_CAROUSEL = "\uE8EB"
    const val VIEW_COLUMN = "\uE8EC"
    const val VIEW_COMFY = "\uE42A"
    const val VIEW_COMPACT = "\uE42B"
    const val VIEW_HEADLINE = "\uE8EE"
    const val DRAG_INDICATOR = "\uE945"

    // 特殊功能图标
    const val PICTURE_IN_PICTURE = "\uE8AA"
    const val CAST = "\uE307"
    const val FULLSCREEN = "\uE5D0"
    const val FULLSCREEN_EXIT = "\uE5D1"
    const val SUBTITLES = "\uE048"
    const val PLAYLIST_PLAY = "\uE05F"
    const val PLAYLIST_ADD = "\uE03B"
    const val FOLDER = "\uE2C7"
    const val FILE = "\uE24D"
    const val CLOUD = "\uE2BD"
    const val CLOUD_DOWNLOAD = "\uE2C0"
    const val CLOUD_UPLOAD = "\uE2C3"
    const val CLOUD_SYNC = "\uEB5A"
    const val CLOUD_DONE = "\uE2BF"
    const val CLOUD_OFF = "\uE2C1"
    const val WIFI = "\uE63E"
    const val WIFI_OFF = "\uE648"
    const val BLUETOOTH = "\uE1A7"
    const val BLUETOOTH_CONNECTED = "\uE1A8"
    const val BLUETOOTH_DISABLED = "\uE1A9"
    const val LOCATION_ON = "\uE0C8"
    const val LOCATION_OFF = "\uE0C7"
    const val GPS_FIXED = "\uE1B3"
    const val GPS_NOT_FIXED = "\uE1B4"
    const val GPS_OFF = "\uE1B5"

    // 文件和文件夹图标
    const val FOLDER_OPEN = "\uE2C8"
    const val FOLDER_SHARED = "\uE2C9"
    const val FOLDER_SPECIAL = "\uE617"
    const val CREATE_NEW_FOLDER = "\uE2CC"
    const val DRIVE_FILE_MOVE = "\uE675"
    const val DRIVE_FILE_RENAME = "\uE675"
    const val ATTACHMENT = "\uE2BC"
    const val INSERT_DRIVE_FILE = "\uE24D"
    const val INSERT_PHOTO = "\uE251"
    const val INSERT_LINK = "\uE250"
    const val INSERT_CHART = "\uE24B"
    const val INSERT_COMMENT = "\uE24C"
    const val INSERT_EMOTICON = "\uE24E"

    // 设置和工具图标
    const val SETTINGS_APPLICATIONS = "\uE8B9"
    const val SETTINGS_BACKUP_RESTORE = "\uE8BA"
    const val SETTINGS_BLUETOOTH = "\uE8BB"
    const val SETTINGS_BRIGHTNESS = "\uE8BD"
    const val SETTINGS_CELL = "\uE8BC"
    const val SETTINGS_ETHERNET = "\uE8BE"
    const val SETTINGS_INPUT_ANTENNA = "\uE8BF"
    const val SETTINGS_INPUT_COMPONENT = "\uE8C0"
    const val SETTINGS_INPUT_HDMI = "\uE8C2"
    const val SETTINGS_INPUT_SVIDEO = "\uE8C3"
    const val SETTINGS_OVERSCAN = "\uE8C4"
    const val SETTINGS_PHONE = "\uE8C5"
    const val SETTINGS_POWER = "\uE8C6"
    const val SETTINGS_REMOTE = "\uE8C7"
    const val SETTINGS_VOICE = "\uE8C8"
    const val TUNE = "\uE429"
    const val BUILD = "\uF8CD"
    const val CODE = "\uE86F"
    const val DEVELOPER_MODE = "\uE1B0"
    const val TERMINAL = "\uF8A3"
    const val ADB = "\uE60E"

    // 其他常用图标
    const val STAR = "\uE838"
    const val STAR_BORDER = "\uE83A"
    const val STAR_HALF = "\uE839"
    const val STAR_OUTLINE = "\uE83A"
    const val STAR_RATE = "\uE8D0"
    const val VISIBILITY = "\uE8F4"
    const val VISIBILITY_OFF = "\uE8F5"
    const val LANGUAGE = "\uE894"
    const val NOTIFICATIONS = "\uE7F4"
    const val NOTIFICATIONS_ACTIVE = "\uE7F7"
    const val NOTIFICATIONS_OFF = "\uE7F6"
    const val NOTIFICATIONS_PAUSED = "\uE7F8"
    const val HELP = "\uE887"
    const val HELP_CENTER = "\uF716"
    const val HELP_OUTLINE = "\uE8FD"
    const val BOOKMARK = "\uE866"
    const val BOOKMARK_BORDER = "\uE867"
    const val BOOKMARK_ADD = "\uE598"
    const val BOOKMARKS = "\uE98B"
    const val DESCRIPTION = "\uE873"
    const val ARTICLE = "\uEF42"
    const val ASSIGNMENT = "\uE85D"
    const val RECEIPT = "\uE8B0"
    const val RECEIPT_LONG = "\uEF6E"
    const val GRADING = "\uEA4F"
    const val PLAGIARISM = "\uEA5A"
    const val CALCULATE = "\uEA5F"
    const val FUNCTIONS = "\uE289"
    const val FUNCTIONS_OUTLINED = "\uE289"
    const val FUNCTIONS_FILLED = "\uE289"
    const val CALENDAR_TODAY = "\uE935"
    const val CALENDAR_MONTH = "\uEBCC"
    const val CALENDAR_VIEW_MONTH = "\uEFE7"
    const val CALENDAR_VIEW_WEEK = "\uEFE8"
    const val CALENDAR_VIEW_DAY = "\uE936"
    const val TODAY = "\uE8DF"
    const val EVENT = "\uE878"
    const val EVENT_NOTE = "\uE616"
    const val EVENT_AVAILABLE = "\uE614"
    const val EVENT_BUSY = "\uE615"
    const val ALARM = "\uE855"
    const val ALARM_ON = "\uE858"
    const val ALARM_OFF = "\uE857"
    const val TIMER = "\uE425"
    const val TIMER_OFF = "\uE426"
    const val WATCH_LATER = "\uE924"
    const val ACCESS_TIME = "\uEFD6"
    const val ACCESS_TIME_FILLED = "\uEFD6"
    const val ACCESS_ALARM = "\uE855"
    const val ACCESS_ALARMS = "\uE855"
}
